version: "3.3"
services:
  ciftools:
    image: ghcr.io/cheminfo-py/crystal_analysis_webservice:latest
    restart: always
    environment:
      - PORT=${PORT}
    ports:
      - 127.0.0.1:${PORT}:${PORT}
